"""empty message

Revision ID: 5274e730092d
Revises: 
Create Date: 2023-09-24 02:29:53.456810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5274e730092d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('borrowed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn_number', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.Integer(), nullable=False),
    sa.Column('borrowed_date', sa.Date(), nullable=False),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['author_name'], ['book.author'], ),
    sa.ForeignKeyConstraint(['book_name'], ['book.title'], ),
    sa.ForeignKeyConstraint(['isbn_number'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['member_name'], ['member.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowed')
    op.drop_table('member')
    op.drop_table('book')
    # ### end Alembic commands ###
