"""Remove returned_date column

Revision ID: ba341654cb41
Revises: 5274e730092d
Create Date: 2023-09-24 21:08:39.079885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba341654cb41'
down_revision = '5274e730092d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed', schema=None) as batch_op:
        batch_op.drop_column('returned_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
